format = """
$directory\
$git_branch\
$git_status\
$character"""

[directory]
style = "blue"
truncate_to_repo = false

[git_branch]
format = "[ ($branch)](green)"
symbol = ""

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "yellow"
conflicted = "!"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?"
modified = "*"
staged = "+"
deleted = "-"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
